# Set all versions
BLASTER_BUILD_TYPE ?= UNOFFICIAL
BLASTER_BUILD_DATE := $(shell date -u +%Y%m%d-%H%M)
BLASTER_VERSION := PixelBLASTER_$(BLASTER_BUILD)-$(PLATFORM_VERSION)-$(BLASTER_BUILD_DATE)-$(BLASTER_BUILD_TYPE)
TARGET_PRODUCT_SHORT := $(subst aosp_,,$(BLASTER_BUILD))
ROM_FINGERPRINT := PixelBlaster/$(PLATFORM_VERSION)/$(TARGET_PRODUCT_SHORT)/$(BLASTER_BUILD_DATE)

PRODUCT_SYSTEM_DEFAULT_PROPERTIES += \
    BUILD_DISPLAY_ID=$(BUILD_ID) \
    ro.pb.version=$(BLASTER_VERSION) \
    ro.pb.build_date=$(BLASTER_BUILD_DATE) \
    ro.pb.build_type=$(BLASTER_BUILD_TYPE) \
    ro.pb.fingerprint=$(ROM_FINGERPRINT)